config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  root to: "pages#home"

  resources :users, only: [ :show ] do
    get 'outfits', to: "users#outfits"
    get 'requests', to: "users#requests"
  end

  resources :outfits

  resources :outfits do
    resources :requests, only: [ :new, :create, :edit, :update, :destroy ]
  end

  get 'outfits', to: 'outfits#index', as: :filtered_outfits

  resources :requests, only: [ :edit, :update ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :outfits
end

app/models/outfit.rb
class Outfit < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :requests, dependent: :destroy

  has_one_attached :photo
  # validates :photo_url, presence: true
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/models/request.rb
class Request < ApplicationRecord
  after_initialize :set_default_status, :if => :new_record?

  def set_default_status
    self.status = 'Pending'
  end

  belongs_to :user
  belongs_to :outfit

  validates :status, inclusion: { in: ["Pending", "Rejected", "Accepted"] }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :outfits, dependent: :destroy
  has_many :requests, through: :outfits, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    @outfits = Outfit.all
    if params[:query].present?
      sql_subquery = "name ILIKE :query OR description ILIKE :query"
      @outfits = @outfits.where(sql_subquery, query: "%#{params[:query]}%")
    elsif params[:category]
      @category = Category.find_by(name: params[:category])
      @outfits = @category ? @category.outfits : Outfit.none
    end
  end

  def show
    @outfit = Outfit.find(params[:id])
    @requests = @outfit.requests
  end

  def new
    @outfit = Outfit.new
  end

  def create
    @outfit = Outfit.new(outfit_params)
    @outfit.user = current_user
    if @outfit.save
      redirect_to outfit_path(@outfit)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @outfit = Outfit.find(params[:id])
  end

  def update
    @outfit = Outfit.find(params[:id])
    if @outfit.update(outfit_params)
      redirect_to outfit_path(@outfit)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @outfit = Outfit.find(params[:id])
    @outfit.destroy
    redirect_to user_path(current_user)
  end

  private

  def outfit_params
    params.require(:outfit).permit(:name, :description, :photo, :price, :category_id)
  end

  def check_user
    @outfit = Outfit.find(params[:id])
    unless @user == @current_user
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_outfit, only: %i[new create]
  before_action :authenticate_user!

  def index
    @requests = current_user.requests
  end

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    @request.user = current_user
    @request.outfit = @outfit
    if @request.save
      redirect_to outfit_path(@request.outfit)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @request = Request.find(params[:id])
    @request.outfit = Outfit.find(params[:outfit_id])
  end

  def update
    @request = Request.find(params[:id])
    @request.update(request_params)
    @request.save!
    redirect_to user_path(current_user)
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to user_path(current_user)
  end

  private

  def set_outfit
    @outfit = Outfit.find(params[:outfit_id])
  end

  def request_params
    params.require(:request).permit(:outfit_id, :status, :start_date, :end_date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @outfits = @user.outfits
    @requests_received = Request.where(outfit: @user.outfits)
    @requests_made = Request.where(user: current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PawsNPals</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "/shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/outfits/_form.html.erb
<%= simple_form_for @outfit do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.input :price %>


  <%= f.label :category_id %>
  <%= f.collection_select :category_id, Category.all, :id, :name %>

  <br><br>
  <%= f.submit @outfit.new_record? ? "Create Outfit" : "Update Outfit" %>
<% end %>

app/views/outfits/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-paw"></i>
    <% end %>
  <div><%= link_to "Pets 'N Paws", root_path, class: "navbar-brand" %></div>

  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav me-auto">
      <li class="nav-item">

      </li>
      <li class="nav-item">
        <%= link_to "Browse all Outfits", outfits_path, class: "nav-link" %>
      </li>
    </ul>
  </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Your Outfits", outfits_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Your Requests", outfits_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/outfits/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h1 class="text-center"> Edit Outfit </h1>

    <%= render 'form', outfit: @outfit %>
  </div>
</div>

app/views/outfits/index.html.erb
<div class="container-xl">
  <div class="row justify-content-center">
    <h1 class="text-center"> Browse outfits for you and your pet!</h1>
  </div>

  <div class="row justify-content-center mt-4">

    <div class="col-3 p-3 border border-right-secondary">
    <!--Sidebar goes here-->
      <%= form_with url: outfits_path, method: :get, class: "d-flex"  do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Name, category..."
        %>
        <%= submit_tag "🔎", name: "", class: "btn btn-secondary" %>
      <% end %>
    </div>

    <div class="col-9 d-flex flex-wrap">
      <div class="container">
        <div class="row justify-content-center", style="row-gap: 1.3rem;">
          <% @outfits.each do |outfit| %>
            <div class="col-4">
              <div class="card outfit-index-card">
                <% if outfit.photo.attached? %>
                  <%= cl_image_tag outfit.photo.key, :gravity=>"auto:0", :crop=>"thumb" %>
                <% end %>
                <div class="card-body">
                  <h5 class="card-title"><%= outfit.name %></h5>
                  <p class="card-text"><strong>Price:</strong><span class="ms-1">$<%= outfit.price %>/day</span></p>
                  <p class="card-text"><strong>Category:</strong><span class="ms-1"><%= outfit.category.name %></span></p>
                  <%= link_to 'More info', outfit_path(outfit) %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  </div>

</div>

app/views/outfits/new.html.erb
<div class="container mt-4">
  <div class="row gy-4">
    <div class="col-12 col-md-6 p-4">
      <h1><%= @outfit.name %></h1>
      <img class="rounded-4" src="https://hips.hearstapps.com/hmg-prod/images/dog-and-owner-costumes-taco-bell-fire-sauce-and-burrito-1652390014.jpg" style="width: -moz-available;">
    </div>
    <div class="col-12 col-md-6 p-4">
      <h1>Create an outfit</h1>
      <%= render 'form', outfit: @outfit %>
      </div>
  </div>
</div>

app/views/outfits/show.html.erb
<div class="container mt-4">
  <div class="row gy-4">
    <div class="col-12 col-md-6 p-4">
      <h1><%= @outfit.name %></h1>
      <div class="outfit-show-img"><%= cl_image_tag(@outfit.photo.key, crop: :fill) %></div>
    </div>

    <div class="col-12 col-md-6 p-4">
      <h1>Outfit details</h1>
      <p class="card-text"><strong>Description: </strong><%= @outfit.description %></p>
      <p class="card-text"><strong>Price: </strong>$<%= @outfit.price %>/day</p>
      <p class="card-text"><strong>Category: </strong> <%= @outfit.category.name %></p>
      <div>
        <%= link_to "Request this outfit!",  new_outfit_request_path(@outfit), :class => "btn btn-primary" %>
        <%= link_to "Go Back to Browse", outfits_path, :class => "btn btn-secondary" %>
        <%= link_to 'Edit', edit_outfit_path(@outfit), class: 'btn btn-info' if @outfit.user == current_user %>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row justify-content-center" style="margin-left: 0px;margin-right: 0px;">
  <div class="col-10">
    <div class="rounded-4 banner">
      <div class="banner-text">
        <h1>Cute matching outfits for your and your pet</h1>
        <p>Twinning w/ with your BFFL never felt better</p>
        <%= link_to "Browse All Outfits", outfits_path(@outfit), :class => "btn btn-light rounded-3 mt-3" %></a>
      </div>
    </div>

    <div class="container my-4">
      <div class="row">

        <div class="col-md-4 mb-3">
          <div class="rounded-4 category-banner-dog">
            <div class="category-banner-text">
              <h3><%= link_to "Dog outfits", filtered_outfits_path(category: 'Dog'), class: 'font-weight-bold text-decoration-none text-white' %></h3>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-3">
          <div class="rounded-4 category-banner-cat">
            <div class="category-banner-text">
              <h3><%= link_to "Cat outfits", filtered_outfits_path(category: 'Cat'), class: 'font-weight-bold text-decoration-none text-white' %></h3>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-3">
          <div class="rounded-4 category-banner-misc">
            <div class="category-banner-text">
              <h3><%= link_to "Miscellaneous", filtered_outfits_path(category: 'Miscellaneous'), class: 'font-weight-bold text-decoration-none text-white' %></h3>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/requests/_form.html.erb
<%= simple_form_for [@outfit, @request] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit "Request this outfit" %>
<% end %>

app/views/requests/edit.html.erb
<div class="container mt-4">

  <div class="row justify-content-center">
    <div class="col-4 col-lg-6">

    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-4 col-lg-6 p-5">
      <h1><%= @request.outfit.name %></h1>
      <div class="outfit-show-img"><%= cl_image_tag(@request.outfit.photo.key, crop: :fill) %></div>
    </div>

    <div class="col-4 col-lg-6 p-5">
      <p>Status: <%= @request.status %></p>
      <p>From: <%= @request.user.username %></p>
      <p>Start date: <%= @request.start_date %></p>
      <p>End date: <%= @request.end_date %></p>

      <%= simple_form_for [@outfit, @request] do |f| %>
        <%= f.input :status, :collection => ['Accepted', 'Rejected'] %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.submit "Submit changes" %>
      <% end %>
    </div>

  </div>

</div>

app/views/requests/new.html.erb
<div class="container mt-4">
  <div class="row gy-4">
    <div class="col-12 col-md-6 p-4">
      <h1><%= @outfit.name %></h1>
      <img class="rounded-4" src="<%= @outfit.photo_url %>" style="width: -moz-available;">
      <strong>Description:</strong> <%= @outfit.description %>
      <br>
      <strong>Price:</strong> $<%= @outfit.price %>/day
    </div>
    <div class="col-12 col-md-6 p-4">
      <h1>Request this outfit</h1>
      <%= render 'form' %>
      </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="text-center text-white" style="background-color: #f1f1f1;">
  <!-- Copyright -->
  <div class="text-center text-dark p-3" style="background-color: rgba(0, 0, 0, 0.1);">
    <a class="text-dark" style="text-decoration: none;" href="https://lewagon.com/">Made with love @ <strong>Le Wagon Montreal</strong></a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-paw"> Paws 'N Pals</i>
    <% end %>

  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav me-auto">
      <li class="nav-item">

      </li>
      <li class="nav-item">
        <%= link_to "Browse all Outfits", outfits_path, class: "nav-link" %>
      </li>
    </ul>
  </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Lease an outfit!", new_outfit_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
              <%= image_tag "https://img.freepik.com/free-vector/cute-cool-cat-wearing-glasses-cartoon-vector-icon-illustration-animal-nature-icon-concept-isolated_138676-4268.jpg?w=1380&t=st=1699721451~exp=1699722051~hmac=04f3220a3d6fbfb234d0284520af505712d79b1fe0ebe86913132d3c62e477f8", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Logout", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">

  <div class="row justify-content-center">
    <h1 class="text-center"><%= @user.username %>'s Profile</h1>
  </div>

  <div class="row mt-4">

    <% if user_signed_in? && current_user.id == @user.id %>
      <h2>Your Outfits</h2>
    <% else %>
      <h2><%= @user.username %>'s outfits for rent</h2>
    <% end %>

    <!-- Cards -->
    <div class="row">
      <% @outfits.each do |outfit| %>
        <div class="col-6 col-lg-4">
          <div class="card user-show-card">
          <% if outfit.photo.attached? %>
            <%= cl_image_tag outfit.photo.key, :gravity=>"auto:0", :crop=>"thumb" %>
          <% end %>
            <div class="card-body">
              <h5 class="card-title"><strong><%= outfit.name %></strong></h5>
              <p class="card-text"><strong>Price: </strong>$<%= outfit.price %>/day</p>
              <!--Edit/Destroy/Show logic-->
              <div class="card-buttons" style="display: flex;">
                <% if user_signed_in? && current_user.id == @user.id %>
                  <%= link_to 'View', outfit_path(outfit)%>
                  <%= link_to 'Edit', edit_outfit_path(outfit)%>
                  <%= link_to 'Delete', outfit_path(outfit), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
                <% else %>
                  <%= link_to 'More info', outfit_path(outfit) %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <% if user_signed_in? && current_user == @user %>

    <!--Made-->
    <div class="row mt-4">
      <h2>Requests You've Made</h2>
      <div class="row">
        <% @requests_made.each do |request| %>
          <div class="col-6 col-md-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><%= request.outfit.name %></h5><p class="card-text">By: <%= request.outfit.user.username %></p>
                <p class="card-text">Status: <%= request.status %></p>
                <p class="card-text">From: <%= request.start_date %> To: <%= request.end_date %></p>
                <%= link_to 'Delete request', outfit_request_path(request.outfit, request), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this request?"}%>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <!--Received-->
    <div class="row mt-4">
      <h2>Received Requests</h2>
      <div class="row">
        <% @requests_received.each do |request| %>
          <div class="col-6 col-md-4">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title"><%= request.outfit.name %></h5>
                <p class="card-text"><%= request.status %></p>
                <p class="card-text">From: <%= request.start_date %> To: <%= request.end_date %></p>
                <p class="card-text">By: <%= request.user.username %></p>
                <%= link_to 'Edit Request', edit_outfit_request_path(request.outfit, request) %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

  <% end %>

</div>